# Directorios dentro del contenedor (persisten vía volúmenes Docker)
metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"
db_engine = "sqlite"

# OJO: replication_factor = 1 => sin redundancia. Ideal para empezar, no para datos críticos.
replication_factor = 1

# RPC interno del cluster
rpc_bind_addr = "0.0.0.0:3901"
rpc_public_addr = "garage:3901"   # nombre del servicio en docker-compose

# Genera esto en el servidor:
#   openssl rand -hex 32
rpc_secret = "799ba0c99febd1a1793b9e1a5a16d713bcfde5c087be29cd81c8a69c0fcb6913"

[s3_api]
# Región lógica para Garage
s3_region = "garage"
# Puerto S3
api_bind_addr = "0.0.0.0:3900"
# Solo se usa si quieres virtual-host (bucket.dominio...), pero no molesta tenerlo.
root_domain = ".s3.garage.localhost"

[s3_web]
bind_addr = "0.0.0.0:3902"
root_domain = ".web.garage.localhost"
index = "index.html"

[admin]
api_bind_addr = "0.0.0.0:3903"

# Genera ambos en el servidor:
#   openssl rand -base64 32
admin_token   = "UkHSNufaZb6wgxoUeXSWaYlNVCYqf8bRys/u+r2mF+g="
metrics_token = "d3YGRbdrDs8BIUG6wTUEpaqMIYaFzUjKH6cZ6xRhBOM="
metrics_require_token = true
